<?php

namespace Nebatech\Controllers\Academic;

use Nebatech\Core\Controller;
use Nebatech\Repositories\ApplicationRepository;
use Nebatech\Services\NotificationService;
use Nebatech\Middleware\AuthMiddleware;

class ApplicationController extends Controller
{
    private ApplicationRepository $applicationRepo;
    private NotificationService $notificationService;

    public function __construct()
    {
        $this->applicationRepo = new ApplicationRepository();
        $this->notificationService = new NotificationService();
    }

    /**
     * Show application form
     */
    public function showApplicationForm(): void
    {
        try {
            $program = $_GET['program'] ?? '';

            // Check if user already has pending application
            $userId = AuthMiddleware::userId();
            
            // Load programs from config
            $programsConfig = require dirname(__DIR__, 3) . '/config/programs.php';
            
            echo $this->view('applications/create', [
                'program' => $program,
                'programs' => $programsConfig,
                'user' => \Nebatech\Models\User::findById($userId)
            ]);
        } catch (\Exception $e) {
            error_log("Error in showApplicationForm: " . $e->getMessage());
            $userId = AuthMiddleware::userId();
            $user = \Nebatech\Models\User::findById($userId);
            echo $this->view('applications/create', [
                'program' => '',
                'programs' => $this->getAvailablePrograms(),
                'user' => $user ?? []
            ]);
        }
    }

    /**
     * Submit application
     */
    public function submitApplication(): void
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            $this->redirect('/apply');
            return;
        }

        try {
            $userId = AuthMiddleware::userId();
            $user = \Nebatech\Models\User::findById($userId);
            
            // Validate input
            $program = $_POST['program'] ?? '';
            $educationalBackground = $_POST['educational_background'] ?? '';
            $motivationStatement = $_POST['motivation_statement'] ?? '';
            $referralSource = $_POST['referral_source'] ?? '';

            if (empty($program) || empty($educationalBackground) || empty($motivationStatement)) {
                $this->redirect('/apply?error=missing_fields');
                return;
            }

            // Validate minimum lengths
            if (strlen($educationalBackground) < 50) {
                $this->redirect('/apply?error=education_too_short');
                return;
            }

            if (strlen($motivationStatement) < 100) {
                $this->redirect('/apply?error=motivation_too_short');
                return;
            }

            // Handle document upload
            $documentPath = null;
            if (isset($_FILES['document']) && $_FILES['document']['error'] === UPLOAD_ERR_OK) {
                $documentPath = $this->uploadDocument($_FILES['document'], $userId);
                if (!$documentPath) {
                    $this->redirect('/apply?error=invalid_document');
                    return;
                }
            }

            // Create application with user data
            // Note: UUID is automatically generated by Application::create()
            $applicationData = [
                'user_id' => $userId,
                'first_name' => $user['first_name'],
                'last_name' => $user['last_name'],
                'email' => $user['email'],
                'phone' => $user['phone'] ?? null,
                'country' => $user['location'] ?? null,
                'program' => $program,
                'educational_background' => $educationalBackground,
                'motivation_statement' => $motivationStatement,
                'referral_source' => $referralSource,
                'document_path' => $documentPath,
                'status' => 'pending'
            ];

            $applicationId = \Nebatech\Models\Application::create($applicationData);

            if ($applicationId) {
                // Get the created application
                $application = \Nebatech\Models\Application::findById($applicationId);
                
                // Send notification
                if ($application) {
                    $this->notificationService->notifyApplicationReceived($userId, $application);
                }
                
                $this->redirect('/my-applications?success=application_submitted');
            } else {
                $this->redirect('/apply?error=submission_failed');
            }
        } catch (\Exception $e) {
            error_log("Error submitting application: " . $e->getMessage());
            $this->redirect('/apply?error=submission_failed');
        }
    }

    /**
     * View user's applications
     */
    public function myApplications(): void
    {
        try {
            $userId = AuthMiddleware::userId();
            $user = \Nebatech\Models\User::findById($userId);
            $applications = $this->applicationRepo->getAll(['user_id' => $userId]);

            echo $this->view('applications/my-applications', [
                'applications' => $applications ?? [],
                'user' => $user
            ]);
        } catch (\Exception $e) {
            error_log("Error in myApplications: " . $e->getMessage());
            $userId = AuthMiddleware::userId();
            $user = \Nebatech\Models\User::findById($userId);
            echo $this->view('applications/my-applications', [
                'applications' => [],
                'user' => $user ?? []
            ]);
        }
    }

    /**
     * View single application
     */
    public function viewApplication(string $uuid): void
    {
        try {
            $application = \Nebatech\Models\Application::findByUuid($uuid);

            if (!$application) {
                $this->redirect('/my-applications?error=not_found');
                return;
            }

            // Check if user owns this application
            $userId = AuthMiddleware::userId();
            if ($application['user_id'] !== $userId) {
                $this->redirect('/my-applications?error=unauthorized');
                return;
            }

            echo $this->view('applications/view', [
                'application' => $application,
                'user' => \Nebatech\Models\User::findById($userId)
            ]);
        } catch (\Exception $e) {
            error_log("Error in viewApplication: " . $e->getMessage());
            $this->redirect('/my-applications?error=not_found');
        }
    }

    /**
     * Show update application form
     */
    public function showUpdateForm(string $uuid): void
    {
        try {
            $application = \Nebatech\Models\Application::findByUuid($uuid);

            if (!$application) {
                $this->redirect('/my-applications?error=not_found');
                return;
            }

            // Check if user owns this application
            $userId = AuthMiddleware::userId();
            if ($application['user_id'] !== $userId) {
                $this->redirect('/my-applications?error=unauthorized');
                return;
            }

            // Only allow updates if status is 'info_requested'
            if ($application['status'] !== 'info_requested') {
                $this->redirect('/application/' . $uuid . '?error=cannot_update');
                return;
            }

            // Load programs from config
            $programsConfig = require dirname(__DIR__, 3) . '/config/programs.php';

            echo $this->view('applications/update', [
                'application' => $application,
                'programs' => $programsConfig,
                'user' => \Nebatech\Models\User::findById($userId)
            ]);
        } catch (\Exception $e) {
            error_log("Error in showUpdateForm: " . $e->getMessage());
            $this->redirect('/my-applications?error=not_found');
        }
    }

    /**
     * Update application (if info requested)
     */
    public function updateApplication(string $uuid): void
    {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            $this->redirect('/application/' . $uuid . '/update');
            return;
        }

        try {
            $userId = AuthMiddleware::userId();
            $application = \Nebatech\Models\Application::findByUuid($uuid);

            if (!$application || $application['user_id'] !== $userId) {
                $this->redirect('/my-applications?error=unauthorized');
                return;
            }

            // Only allow updates if status is 'info_requested'
            if ($application['status'] !== 'info_requested') {
                $this->redirect('/my-applications?error=cannot_update');
                return;
            }

            $data = [
                'educational_background' => $_POST['educational_background'] ?? $application['educational_background'],
                'motivation_statement' => $_POST['motivation_statement'] ?? $application['motivation_statement'],
                'referral_source' => $_POST['referral_source'] ?? $application['referral_source'],
                'status' => 'pending' // Reset to pending after update
            ];

            // Handle new document upload
            if (isset($_FILES['document']) && $_FILES['document']['error'] === UPLOAD_ERR_OK) {
                $documentPath = $this->uploadDocument($_FILES['document'], $userId);
                if ($documentPath) {
                    $data['document_path'] = $documentPath;
                }
            }

            $success = \Nebatech\Models\Application::updateByUuid($uuid, $data);

            if ($success) {
                $this->redirect('/application/' . $uuid . '?success=updated');
            } else {
                $this->redirect('/application/' . $uuid . '/update?error=update_failed');
            }
        } catch (\Exception $e) {
            error_log("Error updating application: " . $e->getMessage());
            $this->redirect('/application/' . $uuid . '/update?error=update_failed');
        }
    }

    /**
     * Upload document
     */
    private function uploadDocument(array $file, int $userId): ?string
    {
        $uploadDir = __DIR__ . '/../../storage/uploads/applications/';
        
        // Create directory if it doesn't exist
        if (!is_dir($uploadDir)) {
            mkdir($uploadDir, 0755, true);
        }

        // Generate unique filename
        $extension = pathinfo($file['name'], PATHINFO_EXTENSION);
        $filename = 'app_' . $userId . '_' . time() . '.' . $extension;
        $filepath = $uploadDir . $filename;

        // Validate file type (PDF, DOC, DOCX, JPG, PNG)
        $allowedTypes = ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'];
        if (!in_array(strtolower($extension), $allowedTypes)) {
            return null;
        }

        // Validate file size (max 5MB)
        if ($file['size'] > 5 * 1024 * 1024) {
            return null;
        }

        if (move_uploaded_file($file['tmp_name'], $filepath)) {
            return '/storage/uploads/applications/' . $filename;
        }

        return null;
    }

    /**
     * Download application document
     */
    public function downloadDocument(string $file = ''): void
    {
        try {
            if (empty($file)) {
                http_response_code(404);
                echo "File not found";
                return;
            }

            // Sanitize filename to prevent directory traversal
            $filename = basename($file);
            $filepath = __DIR__ . '/../../storage/uploads/applications/' . $filename;

            // Check if file exists
            if (!file_exists($filepath)) {
                http_response_code(404);
                echo "File not found";
                return;
            }

            // Verify user has permission to access this file
            $userId = AuthMiddleware::userId();
            $userRole = $_SESSION['user']['role'] ?? '';
            
            // Extract user ID from filename (format: app_{userId}_{timestamp}.{ext})
            if (preg_match('/^app_(\d+)_/', $filename, $matches)) {
                $fileUserId = (int)$matches[1];
                
                // Allow access if user owns the file, or is admin/facilitator
                if ($fileUserId !== $userId && !in_array($userRole, ['admin', 'facilitator'])) {
                    http_response_code(403);
                    echo "Access denied";
                    return;
                }
            }

            // Get file info
            $finfo = finfo_open(FILEINFO_MIME_TYPE);
            $mimeType = finfo_file($finfo, $filepath);
            finfo_close($finfo);

            // Set headers for file download
            header('Content-Type: ' . $mimeType);
            header('Content-Disposition: inline; filename="' . basename($filepath) . '"');
            header('Content-Length: ' . filesize($filepath));
            header('Cache-Control: private, max-age=3600');
            
            // Output file
            readfile($filepath);
            exit;

        } catch (\Exception $e) {
            error_log("Error downloading document: " . $e->getMessage());
            http_response_code(500);
            echo "Error downloading file";
        }
    }

    /**
     * Get available programs
     */
    private function getAvailablePrograms(): array
    {
        return [
            'frontend-development' => 'Front-End Development',
            'backend-development' => 'Back-End Development',
            'fullstack-development' => 'Full-Stack Development',
            'database-administration' => 'Database Administration',
            'introduction-to-ai' => 'Introduction to AI',
            'machine-learning-basics' => 'Machine Learning Basics',
            'microsoft-office' => 'Microsoft Office',
            'digital-literacy' => 'Digital Literacy'
        ];
    }
}
