-- Add individual Frontend courses
INSERT INTO courses (uuid, title, slug, description, level, duration_hours, status, card_color_from, card_color_to, card_modules, card_features, card_duration, card_icon, instructor_name, enrollment_count, rating, review_count, is_new, category, price, facilitator_name, created_at) VALUES
(UUID(), 'HTML & CSS Fundamentals', 'html-css-fundamentals', 'Learn the building blocks of web development with HTML5 and CSS3.', 'Beginner', 40, 'published', 'from-orange-500', 'to-orange-600', 8, 'Hands-on projects', '40 hours', 'fas fa-code', 'Nebatech Team', 3500, 4.7, 2845, 0, 'Development', 590.00, 'Sarah Chen', NOW()),
(UUID(), 'JavaScript Essentials', 'javascript-essentials', 'Master JavaScript from basics to advanced concepts and ES6+ features.', 'Beginner', 60, 'published', 'from-yellow-500', 'to-yellow-600', 12, 'Interactive coding', '60 hours', 'fab fa-js', 'Nebatech Team', 5200, 4.8, 4321, 0, 'Development', 950.00, 'Sarah Chen', NOW()),
(UUID(), 'React.js Complete Guide', 'react-js-complete-guide', 'Build powerful web applications with React, Hooks, and modern patterns.', 'Intermediate', 80, 'published', 'from-cyan-500', 'to-blue-600', 15, 'Real-world projects', '80 hours', 'fab fa-react', 'Nebatech Team', 4800, 4.9, 3567, 0, 'Development', 1550.00, 'Sarah Chen', NOW()),
(UUID(), 'Vue.js Mastery', 'vue-js-mastery', 'Learn Vue 3, Composition API, Vuex, and build modern SPAs.', 'Intermediate', 70, 'published', 'from-green-500', 'to-green-600', 14, 'Build SPAs', '70 hours', 'fab fa-vuejs', 'Nebatech Team', 3200, 4.6, 1940, 0, 'Development', 1430.00, 'Sarah Chen', NOW()),
(UUID(), 'Tailwind CSS Fundamentals', 'tailwind-css-fundamentals', 'Build modern UIs rapidly with utility-first CSS framework.', 'Beginner', 35, 'published', 'from-teal-500', 'to-cyan-600', 7, 'Utility-first CSS', '35 hours', 'fas fa-palette', 'Nebatech Team', 2800, 4.7, 2145, 0, 'Development', 710.00, 'Sarah Chen', NOW()),
(UUID(), 'Next.js Full Course', 'next-js-full-course', 'Build production-ready React apps with SSR, SSG, and API routes.', 'Advanced', 90, 'published', 'from-gray-800', 'to-black', 18, 'Production-ready apps', '90 hours', 'fas fa-layer-group', 'Nebatech Team', 2500, 4.9, 1680, 0, 'Development', 1790.00, 'Sarah Chen', NOW());

-- Add individual Backend courses
INSERT INTO courses (uuid, title, slug, description, level, duration_hours, status, card_color_from, card_color_to, card_modules, card_features, card_duration, card_icon, instructor_name, enrollment_count, rating, review_count, is_new, category, price, facilitator_name, created_at) VALUES
(UUID(), 'Node.js Fundamentals', 'node-js-fundamentals', 'Build scalable server-side applications with Node.js and Express.', 'Beginner', 50, 'published', 'from-green-600', 'to-green-700', 10, 'RESTful APIs', '50 hours', 'fab fa-node-js', 'Nebatech Team', 4200, 4.7, 3145, 0, 'Development', 890.00, 'Michael Roberts', NOW()),
(UUID(), 'Python Backend Development', 'python-backend-development', 'Master Python, Django, and Flask for web development.', 'Beginner', 60, 'published', 'from-blue-600', 'to-indigo-700', 12, 'Web frameworks', '60 hours', 'fab fa-python', 'Nebatech Team', 5100, 4.8, 4235, 0, 'Development', 1050.00, 'Michael Roberts', NOW()),
(UUID(), 'PHP & Laravel Mastery', 'php-laravel-mastery', 'Build robust web applications with PHP and Laravel framework.', 'Intermediate', 70, 'published', 'from-purple-600', 'to-pink-600', 14, 'MVC architecture', '70 hours', 'fab fa-php', 'Nebatech Team', 3800, 4.6, 2987, 0, 'Development', 1180.00, 'Michael Roberts', NOW()),
(UUID(), 'RESTful API Development', 'restful-api-development', 'Design and build scalable REST APIs with best practices.', 'Intermediate', 45, 'published', 'from-orange-600', 'to-red-600', 9, 'API design patterns', '45 hours', 'fas fa-server', 'Nebatech Team', 3500, 4.7, 2654, 0, 'Development', 780.00, 'Michael Roberts', NOW()),
(UUID(), 'GraphQL Complete Guide', 'graphql-complete-guide', 'Master GraphQL for modern API development.', 'Advanced', 40, 'published', 'from-pink-600', 'to-purple-700', 8, 'Modern APIs', '40 hours', 'fas fa-project-diagram', 'Nebatech Team', 2200, 4.8, 1876, 0, 'Development', 950.00, 'Michael Roberts', NOW()),
(UUID(), 'Microservices Architecture', 'microservices-architecture', 'Build and deploy microservices with Docker and Kubernetes.', 'Advanced', 80, 'published', 'from-indigo-700', 'to-blue-800', 16, 'Cloud-native apps', '80 hours', 'fas fa-cubes', 'Nebatech Team', 1900, 4.9, 1543, 0, 'Development', 1850.00, 'Michael Roberts', NOW());

-- Add individual Database courses
INSERT INTO courses (uuid, title, slug, description, level, duration_hours, status, card_color_from, card_color_to, card_modules, card_features, card_duration, card_icon, instructor_name, enrollment_count, rating, review_count, is_new, category, price, facilitator_name, created_at) VALUES
(UUID(), 'SQL Mastery', 'sql-mastery', 'Master SQL from basics to advanced queries and optimization.', 'Beginner', 45, 'published', 'from-blue-600', 'to-blue-700', 9, 'Query optimization', '45 hours', 'fas fa-database', 'Nebatech Team', 4500, 4.7, 3421, 0, 'Development', 720.00, 'Emily Davis', NOW()),
(UUID(), 'MySQL Administration', 'mysql-administration', 'Learn MySQL database administration, performance tuning, and security.', 'Intermediate', 50, 'published', 'from-orange-600', 'to-orange-700', 10, 'Performance tuning', '50 hours', 'fas fa-cog', 'Nebatech Team', 2800, 4.6, 2145, 0, 'Development', 850.00, 'Emily Davis', NOW()),
(UUID(), 'MongoDB Complete Guide', 'mongodb-complete-guide', 'Master NoSQL with MongoDB for modern applications.', 'Intermediate', 40, 'published', 'from-green-600', 'to-green-700', 8, 'NoSQL design', '40 hours', 'fas fa-leaf', 'Nebatech Team', 3200, 4.8, 2567, 0, 'Development', 950.00, 'Emily Davis', NOW()),
(UUID(), 'PostgreSQL Advanced', 'postgresql-advanced', 'Advanced PostgreSQL features and performance optimization.', 'Advanced', 35, 'published', 'from-blue-700', 'to-indigo-800', 7, 'Advanced features', '35 hours', 'fas fa-elephant', 'Nebatech Team', 1800, 4.7, 1432, 0, 'Development', 780.00, 'Emily Davis', NOW());

-- Add individual Digital Literacy courses
INSERT INTO courses (uuid, title, slug, description, level, duration_hours, status, card_color_from, card_color_to, card_modules, card_features, card_duration, card_icon, instructor_name, enrollment_count, rating, review_count, is_new, category, price, facilitator_name, created_at) VALUES
(UUID(), 'Computer Basics', 'computer-basics', 'Essential computer skills for beginners.', 'Beginner', 20, 'published', 'from-blue-500', 'to-blue-600', 4, 'Hands-on practice', '20 hours', 'fas fa-desktop', 'Nebatech Team', 5200, 4.5, 4123, 0, 'Office Skills', 350.00, 'Jessica Turner', NOW()),
(UUID(), 'Internet & Email Skills', 'internet-email-skills', 'Master web browsing, email, and online safety.', 'Beginner', 15, 'published', 'from-green-500', 'to-green-600', 3, 'Online safety', '15 hours', 'fas fa-globe', 'Nebatech Team', 4800, 4.6, 3845, 0, 'Office Skills', 290.00, 'Jessica Turner', NOW()),
(UUID(), 'Digital Communication', 'digital-communication', 'Effective digital communication and collaboration tools.', 'Beginner', 18, 'published', 'from-purple-500', 'to-purple-600', 4, 'Collaboration tools', '18 hours', 'fas fa-comments', 'Nebatech Team', 3900, 4.7, 3124, 0, 'Office Skills', 330.00, 'Jessica Turner', NOW());
